# Generated by Django 3.2.9 on 2021-11-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_post_postparagraph_postsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='brief_content',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
